name: CI - Verify

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - runtime: node
            node-version: 20.x
          - runtime: node
            node-version: 22.x
          - runtime: node
            node-version: 24.x  
          - runtime: bun
          - runtime: deno
    steps:
      - uses: actions/checkout@v7
      - name: Nodejs
        if: matrix.runtime == 'node'
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - if: matrix.runtime == 'node'
        run: |
          npm install
          npm run test
      - name: Bun
        if: matrix.runtime == 'bun'
        uses: oven-sh/setup-bun@v1
      - if: matrix.runtime == 'bun'
        run: |
          bun install
          npm run test
      - name: Deno
        if: matrix.runtime == 'deno'
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - if: matrix.runtime == 'deno'
        run: |
          deno install
          npm run test

  publish:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      id-token: write
      attestations: write
      packages: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm run build
      - name: Generate provenance
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: dist/**
      - name: Verify npm publish
        run: npm publish --provenance --dry-run || true
