name: CI - Verify

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - runtime: node
            node-version: 20.x
          - runtime: node
            node-version: 22.x
          - runtime: node
            node-version: 24.x  
          - runtime: bun
          - runtime: deno
    steps:
      - uses: actions/checkout@v7
      - name: Setup pnpm
        if: matrix.runtime == 'node'
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Nodejs
        if: matrix.runtime == 'node'
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - if: matrix.runtime == 'node'
        run: |
          pnpm install --frozen-lockfile
          pnpm test
      - name: Bun
        if: matrix.runtime == 'bun'
        uses: oven-sh/setup-bun@v2
      - if: matrix.runtime == 'bun'
        run: |
          bun install
          bun test
      - name: Deno
        if: matrix.runtime == 'deno'
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - if: matrix.runtime == 'deno'
        run: |
          deno install
          deno test

  publish:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      id-token: write
      attestations: write
      packages: write
    steps:
      - uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v7
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Build package
        run: pnpm run build
      - name: Generate provenance
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: dist/**
      - name: Verify npm publish
        run: pnpm publish --dry-run --no-git-checks || true