name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build
      - name: Generate provenance
        uses: actions/attest-build-provenance@v1
        env:
          # actions/attest-build-provenance@v1 uses Node 20
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        with:
          subject-path: dist/**
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
